### ISSUE TITLE
No such command "shell"

### ISSUE THREAD

**Issue by pmourer** [phpenv/phpenv#101]
When trying to set the shell version, i get an error.

```
$ phpenv help
phpenv:
=======
   PHP multi-version installation and management utility.

Usage: phpenv <command> [<args>]

Some useful phpenv commands are:
   commands    List all available phpenv commands
   configure   Edit the current PHP's php.ini configuration file at location
   local       Set or show the local application-specific PHP version
   global      Set or show the global PHP version and update the Apache apxs
   shell       Set or show the shell-specific PHP version
   install     Install a PHP version using the php-build plugin
   uninstall   Uninstall a specific PHP version using the php-build plugin
   rehash      Rehash phpenv shims (run this after installing executables)
   version     Show the current PHP version and its origin
   versions    List all PHP versions available to phpenv
   which       Display the full path to an executable
   whence      List all PHP versions that contain the given executable

See `phpenv help <command>' for information on a specific command.
For full documentation, see: https://github.com/madumlao/phpenv#readme

$ phpenv -v
phpenv v0.9.0-rc.1

$ phpenv versions
  system
  7.1.33
  7.2.32
* 7.3.20 (set by /home/pauly/.phpenv/version)

$ phpenv shell 7.3.20
phpenv: no such command `shell'

```

**Comment by debo** [comment]
Hi @pmourer that's very strange. I just tried it locally on my machine and it seems to work just fine. Did you setup phpenv properly? Is the PATH set correctly and the shims loaded properly? Do other commands work? Please let us know.

**Comment by pmourer** [comment]
I installed this from the AUR as the phpenv-install package also gave me errors, however now i see the AUR package points to a separate repository that is 3 commits behind the master of this repo (strange). I will try a manual install following the steps here

**Comment by pmourer** [comment]
The repo that the AUR points at this this one: https://github.com/madumlao/phpenv

**Comment by pmourer** [comment]
It looks like that AUR package just copies an executable to /usr/bin, so i'm guessing all those things you highlighted are not set up
```
	mkdir -p "${pkgdir}/usr/bin"
	ln -s "/usr/lib/${pkgname%-git}/libexec/${pkgname%-git}" "${pkgdir}/usr/bin/"
```

**Comment by debo** [comment]
Yeah, it might not, make sure you follow step 2 and 3 [here](https://github.com/phpenv/phpenv#basic-github-checkout)

**Comment by pmourer** [comment]
ok, that did it. not sure if issuing those commands w/ the AUR install would have worked, but i'd prefer to not be tracking a separate repo. Thanks for the help!

**Comment by debo** [comment]
I'm glad it's sorted. Fair shout, in fairness madumlao repo is a fork of this one, you can find the whole story [here](https://github.com/phpenv/phpenv/issues/57) if you want, but now that we eventually managed to get in touch with the original owner and regained control access to this repo, we moved back here. I guess that's a quick fix that @madumlao might have to look at so to point back here instead.
