### ISSUE TITLE
[Suggestion] Consider renaming services to include the PHP version

### ISSUE THREAD

**Issue by pmourer** [phpenv/phpenv#102]

**Comment by debo** [comment]
@pmourer could you please elaborate a bit further, with example, what do you mean by this? Thanks

**Comment by pmourer** [comment]
oh woah haha this was not supposed to have been submitted. closing for now as i figure out my exact workflow here. sorry!

**Comment by pmourer** [comment]
for historical purposes -- what i was trying to accomplish was having multiple PHP fpm versions running at the same time, and i was trying to accomplish this by directly enabling the services withing `~/.phpenv` like this:
```
$ sudo systemctl enable $HOME/.phpenv/versions/7.1.32/etc/systemd/system/php-fpm.service
```
I ran into the issue that then there would be multiple services with the same name. However, the bigger issue i ran into is that the services are always overwritten when a PHP version is rebuilt (ie, i learned i needed an additional module for a particular use case). So i think moving forward, my setup will be to copy these services to `/etc/systend/system` and then also copy the php-fpm.d configs to a neutral location (as those are also overwritten).

**Comment by debo** [comment]
No worries @pmourer. I think when you get to that point then phpenv is probably not the right tool anymore; you probably better exploring virtual machines or containers.

**Comment by pmourer** [comment]
It's true perhaps, and i did try running various client servers in separate docker containers, however then i can really only have one running at a time due to separate nginx instances trying to bind to port 80 (perhaps there is a way around this with a shared nginx instance) and it was extremely resource intensive. I think a "hybrid" of using phpenv and custom services that just point to the PHP version(s) that i want, and my custom php-fpm configs will work for now. I'm quite happy with phpenv overall!
