### ISSUE TITLE
Extending "phpenv versions" to show the latest available version

### ISSUE THREAD

**Issue by RicoFactset** [phpenv/phpenv#103]
Hello,

Would it possible to extend the "phpenv versions" command to show only the latest available version?

Something like: phpenv versions --latest

Thanks
Rico

**Comment by debo** [comment]
Hi @RicoFactset I suppose. so, in fact it's probably worth dropping entirely some of the older version of PHP who are long gone and not supported anymore; however, the latter is more of a task for the php-build team than phpenv because that's what we rely on.

**Comment by RicoFactset** [comment]
@debo Thanks for your answer. Yes I agree. I still would like to have this --latest feature as I build a Jenkins core library which provides developers to choose the PHP version to be installed OR by omitting the version parameter I install the latest PHP version available. So whenever there are multiple versions available and need this method to determine the latest one.

![image](https://user-images.githubusercontent.com/14312210/98520574-82bd6b00-2272-11eb-9022-1c95dbba846f.png)

**Comment by madumlao** [comment]
Apologies for the (1+year) late bump but while this feature makes sense, it's not in the upstream rbenv and should probably be dealt with in other ways as we don't want to actively move away from rbenv.

This kind of feature can easily be answered in a build pipeline by using some equivalent of

~~~
phpenv versions | sort -h | tail -n 1
~~~

Which should be guaranteed to pull the latest version.

I'll mark this closed, but feel free to reopen if you have other comments.
