### ISSUE TITLE
PhpStorm doesn't recognize the PHP version

### ISSUE THREAD

**Issue by dingo-d** [phpenv/phpenv#104]
I'm using WSL2 for development and I've set up the phpenv, and it works nicely. I've switched to PHP 8.0.7, typing `php -v` in my terminal I get

```bash
PHP 8.0.7 (cli) (built: Jun 19 2021 19:42:49) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.7, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
```

I can see my demo Laravel app showing PHP 8, all is fine and well. But, when I try to set up my CLI interpreter in the PHP storm, when trying to set my PHP executable to either

```
/home/dzoljom/.phpenv/versions/8.0.7/bin/php
```

or (from `which php`)

```
/home/dzoljom/.phpenv/shims/php
```

I cannot reload the phpinfo. If I try to manually navigate to the folder, because I've mapped it to a Z drive, I can click on the reload phpinfo icon, but then I'm getting the following error: 

> Cannot run program "Z:\home\dzoljom\.phpenv\shims\php" (in directory "Z:\home\dzoljom\Projects\project\laravel-test"): CreateProcess error=193, %1 is not a valid Win32 application

![image](https://user-images.githubusercontent.com/8638515/122653813-95244f00-d147-11eb-81ca-fd99a1cae86c.png)

Any ideas why this happens? When I use globally installed php from my `/usr/bin/php`, this workes nicely

![image](https://user-images.githubusercontent.com/8638515/122653837-c0a73980-d147-11eb-9169-d4aa59b0303e.png)

**Comment by dingo-d** [comment]
Ok, I realized I have set the path with wrong slashes. When I add `/home/dzoljom/.phpenv/shims/php` it detects the PHP, but not the correct version. It picks up the system php version, not the phpenv one.

**Comment by dingo-d** [comment]
My bad, should have used `phpenv global 8.0.7` and then it works.

**Comment by debo** [comment]
Hi @dingo-d sorry for the late reply. I'm glad you worked it out and that it's all fine now.
