### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by dingo-d** [phpenv/phpenv#105]
Hi! 

I'm wondering how to install the new PHP 8.1 that just came out using phpenv? 

Can I just somehow manually point to the https://www.php.net/distributions/php-8.1.0.tar.bz2 link?

Thanks!

**Comment by debo** [comment]
Hi @dingo-d, the best way would be to wait or replicate [this PR](https://github.com/php-build/php-build/pull/691) locally assuming you are already using the php-build plugin.

**Comment by dingo-d** [comment]
Oh, didn't notice that. Will wait for it to be merged. Thanks!

**Comment by debo** [comment]
No problem at all.
