### ISSUE TITLE
grep: invalid option -- P

### ISSUE THREAD

**Issue by MrZyr0** [phpenv/phpenv#109]
Hi,

I just tried to use [`phpenv`](https://github.com/phpenv/phpenv) but I can't install any version of php.

All my tries result to this:
![Capture d’écran 2022-02-21 à 15 13 56](https://user-images.githubusercontent.com/32927775/154972048-807e1e32-acdc-4d2a-94a6-a0bc08c196a0.png)

Here are the contents of the log file :
```
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
configure: WARNING: unrecognized options: --with-png-dir, --with-libxml-dir, --with-icu-dir
configure: error: Please reinstall the BZip2 distribution
```

I have already tried to install all the dependencies listed in [this PR comment](https://github.com/phpenv/phpenv/issues/6#issuecomment-13405869) without any effect.

I can't install theses libs : `libmagic`, `tidy`, `autoconf213`.

I'm running on a Macbook Pro 13" M1 2020 Monterey 12.2 (21D49)

**Comment by debo** [comment]
Hi @MrZyr0 if you look at the last line it says 
```shell
configure: error: Please reinstall the BZip2 distribution
```
Is that packaged installed? If so, did you make sure the package and more importantly, its libraries are in the path.

**Comment by JeffreyArts** [comment]
Some situation as @MrZyr0, I have got bzip2 installed with homebrew. In previous tries it was complaining that pkg-config & openssl where missing, which I have added via brew and resolved the issue. Mine complains about similar options, it just doesn't complain about --with-libxml-dir. Which makes it sound like there are packages to be installed among the default bzip2 homebrew package, yet I wouldn't know which.

**Comment by debo** [comment]
I know that his possibly not a good answer to give you but, because this seems to be a recurrent issue, did you people had a look at [this thread](https://github.com/phpenv/phpenv/issues/90) instead? I'd advise to start from the bottom because it's quite long and most of the things on the top are probably obsolete by now. Have a look and please let me know how you get along with that and if you might need further assistance.

**Comment by fabiobedeschi** [comment]
I have the same problem. I guess php-build assumes GNU grep is installed, but (on macOS) BSD grep is used by default. However GNU grep can be installed using `brew install grep` which becomes available as `ggrep`.
I have not been able to investigate this further but hope it helps

**Comment by debo** [comment]
So far all the people who had build issues used to be able to resolve by following the thread I linked, but yes you could also be right @fabiobedeschi and in that case you can also change your path to have GNU grep first.

**Comment by MrZyr0** [comment]
Hey 👋 
Sorry for the late response. In the mean time, I've found another projet who works perfectly with brew : [phpbrew](https://github.com/phpbrew/phpbrew)

Sorry for this issue, and for the inconvenience.

You can close this issue if you want to

**Comment by debo** [comment]
Mind you that the two projects are different and offer a different type of functionality and experience, but if phpbrew works ok with you than stick to it :)

I'll close this one then.

**Comment by arthurhess** [comment]
I got it to work by installing GNU grep with MacPorts, and making sure it was first in the PATH.

`export PATH=/opt/local/libexec/gnubin:$PATH`

**Comment by debo** [comment]
Thanks a lot @arthurhess for the update. I'll put this information somewhere in the README or in a troubleshooting section for other people to rely on.
