### ISSUE TITLE
Build Error: PEAR package PHP_Archive

### ISSUE THREAD

**Issue by ajhmdni** [phpenv/phpenv#130]
I'm trying to install PHP version 8.3.4, but it always fails because of a build error by the PHP_Archive package. I've tried looking for a way to solve it on the internet but still can't solve it. this is the build error log

`
phpenv: /home/inadio/.phpenv/versions/8.3.4 already exists
continue with installation? (y/N) y
[Info]: Loaded extension plugin
[Info]: Loaded apc Plugin.
[Info]: Loaded composer Plugin.
[Info]: Loaded github Plugin.
[Info]: Loaded uprofiler Plugin.
[Info]: Loaded xdebug Plugin.
[Info]: Loaded xhprof Plugin.
[Info]: Loaded zendopcache Plugin.
[Info]: php.ini-production gets used as php.ini
[Info]: Building 8.3.4 into /home/inadio/.phpenv/versions/8.3.4
[Skipping]: Already downloaded and extracted https://www.php.net/distributions/php-8.3.4.tar.bz2
[Preparing]: /tmp/php-build/source/8.3.4
[Compiling]: /tmp/php-build/source/8.3.4
[xdebug]: Installing version 3.3.1
[Skipping]: Already downloaded http://xdebug.org/files/xdebug-3.3.1.tgz
[xdebug]: Compiling xdebug in /tmp/php-build/source/xdebug-3.3.1

-----------------
|  BUILD ERROR  |
-----------------

Here are the last 10 lines from the log:

-----------------------------------------
PEAR package PHP_Archive: API Version: 1.1.0 (stable).
PEAR package PHP_Archive: /usr/share/php.
PEAR package PHP_Archive: /usr/share/php/PHP/Archive.php.
-----------------------------------------

The full Log is available at '/tmp/php-build.8.3.4.20240420175909.log'.
[Warn]: Aborting build.
`

I've installed the latest PHP_Archive package but still have the same issue 
Is there any solution of this problem?

**Comment by ajhmdni** [comment]
I have find the way to solve this error, just to run the install-dependencies script from php-build and automatically installing the correct required dependencies of the plugin, then everything is work properly.

inadio@inad:~/.phpenv/plugins/php-build$ ls -l
total 76
drwxrwxr-x 2 inadio inadio 4096 Apr 20 08:32 bin
-rwxrwxr-x 1 inadio inadio 1261 Apr 20 08:32 build-docs.sh
-rwxrwxr-x 1 inadio inadio 1228 Apr 20 08:32 build-openssl-1.0.sh
-rw-rw-r-- 1 inadio inadio 9694 Apr 20 08:32 CHANGELOG.md
-rw-rw-r-- 1 inadio inadio 2471 Apr 20 08:32 CONTRIBUTING.md
**-rwxrwxr-x 1 inadio inadio 3204 Apr 20 08:32 install-dependencies.sh**
-rwxrwxr-x 1 inadio inadio  763 Apr 20 08:32 install.sh
-rw-rw-r-- 1 inadio inadio 1088 Apr 20 08:32 LICENSE
-rwxrwxr-x 1 inadio inadio 1110 Apr 20 08:32 make-release.sh
drwxrwxr-x 4 inadio inadio 4096 Apr 20 08:32 man
-rw-rw-r-- 1 inadio inadio 2626 Apr 20 08:32 README.md
-rwxrwxr-x 1 inadio inadio 1779 Apr 20 08:32 run-tests.sh
drwxrwxr-x 3 inadio inadio 4096 Apr 20 08:32 share
drwxrwxr-x 2 inadio inadio 4096 Apr 20 08:32 tests
-rwxrwxr-x 1 inadio inadio  477 Apr 20 08:32 uninstall.sh
-rw-rw-r-- 1 inadio inadio 3860 Apr 20 08:32 Vagrantfile
-rwxrwxr-x 1 inadio inadio  232 Apr 20 08:32 vagrant-init.sh

**Comment by debo** [comment]
Thank you very muhc @ajhmdni for coming back with a solution before we did... we love the community spirit! ❤️
