### ISSUE TITLE
Requirements not listed.

### ISSUE THREAD

**Issue by Drarok** [phpenv/phpenv#51]
I don't seem to be able to find a list of requirements to run this software, so I'm having to try installing a PHP version, fix that error, try again, fix, etc.

So far:
- wget (isn't curl more widely installed these days?)
- bison (~ v2.7)
- readline

**Comment by madumlao** [comment]
Closing as issue is now being tracked in #71.

The current approach being explored is updating the documentation using the phpenv-common-deps-install plugin.
