### ISSUE TITLE
PHP Deprecated: Comments starting with '#' are deprecated

### ISSUE THREAD

**Issue by klarkc** [phpenv/phpenv#78]
### Output
```
PHP Deprecated:  Comments starting with '#' are deprecated in /home/rof/.phpenv/versions/5.5.38/etc/php.ini on line 1946 in Unknown on line 0
PHP Deprecated:  Comments starting with '#' are deprecated in /home/rof/.phpenv/versions/5.5.38/etc/php.ini on line 1953 in Unknown on line 0

hi
```

### Expected Result
```
hi
```

### Command

`phpenv local 5.5`
`php -r 'error_reporting(E_ALL); ini_set("display_errors", "1"); echo "hi\n";`

### Platform

OS: Ubuntu 16.04.2
PHP: 5.5.38

**Comment by klarkc** [comment]
Workaround:

```
find /home/rof/.phpenv/versions/5.5.38/etc/ -name "*.ini" -exec sed -i -re 's/^(\s*)#(.*)/\1;\2/g' {} \;
```

**Comment by madumlao** [comment]
Hi @klarkc ,
Just installed 5.5.38 on the latest phpenv and the issue does not seem to appear. The generated php.ini also does not have any comments starting with `#`. It is likely this was resolved upstream (at PHP).

Closing the issue.
