### ISSUE TITLE
./buildconf: No such file or directory

### ISSUE THREAD

**Issue by bes1002t** [phpenv/phpenv#80]
Hi,

I've already installed php 7.1.8 with phpenv and php-build. My problem is that I wanted to reinstall it with --enable-fpm. But now it aborts and shows this error: php-buid: line 545: ./buildconf: No such file or directory.

Should I remove 7.1.8 before I recompile it?

**Comment by bes1002t** [comment]
A reboot fixed this issue, don't know why.

The problem was that I aborted the first run and restarted it. Perhaps a tmp file was still there or something like that.

**Comment by madumlao** [comment]
Closing this as it seems to have resolved itself.
