### ISSUE TITLE
line 47: php-config: command not found

### ISSUE THREAD

**Issue by nicekiwi** [phpenv/phpenv#96]
When I run `phpenv global 7.1.28` I get:

    ezra@asusbook:~$ phpenv global
    7.1
    /home/ezra/.phpenv/libexec/phpenv-global: line 47: php-config: command not found
    ezra@asusbook:~$ phpenvversions
    phpenvversions: command not found
    ezra@asusbook:~$ phpenv versions
      7.0
      7.0.33
    * 7.1 (set by /home/ezra/.phpenv/version)
      7.1.28
      7.2
      7.2.17
      7.3
      7.3.4
    ezra@asusbook:~$ phpenv global 7.1.28
    7.1.28
    /home/ezra/.phpenv/libexec/phpenv-global: line 47: php-config: command not found
    ezra@asusbook:~$

**Comment by madumlao** [comment]
Your phpenv or shims might not be completely installed, could you try checking the following things:

1) php-build did not completely install the program
- check that `ls $(phpenv prefix)/bin` contains the executable `php-config`
- could be from an old broken combination of phpenv and php-build

2) phpenv was not completely installed
- check manually run the following commands:
~~~
export PATH="$HOME/.phpenv/bin:$PATH"
eval "$(phpenv init -)"
~~~
- retry phpenv global. Does it now work without errors? If so, add the above to your `.profile` or `.bash_profile`, whichever is appropriate; then logout and login

**Comment by debo** [comment]
Also, the command is `phpenv versions` with a space.

**Comment by nicekiwi** [comment]
Number 2 fixed it :)
