### ISSUE TITLE
version install failed on macos Catalina

### ISSUE THREAD

**Issue by epicsagas** [phpenv/phpenv#98]
Cannot build php versions due to there is not libz and the lack of command line pkg tool. 

## OS
```
sw_vers                                                                                                                                                 ─╯
ProductName:	Mac OS X
ProductVersion:	10.15.1
BuildVersion:	19B88
```

## Error log

```
phpenv install 7.1.8                                                                                                                                    ─╯
[Info]: Loaded extension plugin
[Info]: Loaded apc Plugin.
[Info]: Loaded composer Plugin.
[Info]: Loaded github Plugin.
[Info]: Loaded uprofiler Plugin.
[Info]: Loaded xdebug Plugin.
[Info]: Loaded xhprof Plugin.
[Info]: Loaded zendopcache Plugin.
[Info]: php.ini-production gets used as php.ini
[Info]: Building 7.1.8 into /Users/hackme/.phpenv/versions/7.1.8
[Skipping]: Already downloaded and extracted https://secure.php.net/distributions/php-7.1.8.tar.bz2
[Preparing]: /var/tmp/php-build/source/7.1.8

-----------------
|  BUILD ERROR  |
-----------------

Here are the last 10 lines from the log:

-----------------------------------------
configure: error: Cannot find libz
-----------------------------------------
```

## already tried

`xcode-select install`
`brew reinstall zlib`
`phpenv install 7.1.8 --without-libzip`

**Comment by epicsagas** [comment]
## Temporary trouble shooting [**UNSAFE!!** ]

1. disable SIP # reboot with safe mode and run `csrutil disable` on terminal
2. `sudo mount -uw / ` # make writable protected folders until restart
3. `sudo ln -s `xcrun --show-sdk-path`/usr/include /usr/include`
4. `phpenv install {php versions}` as long as you need. 
5. enable SIP `csrutil enable` with safe mode

**Comment by debo** [comment]
Hi @epicsagas I would personally discourage to use your solution. Did you have a look at the other [open issue for Mojave](https://github.com/phpenv/phpenv/issues/90)? The underlying problem is the same. There are few approaches in there but I'd say a good compromise of all those would be the following:
```bash
$ brew install autoconf bison bzip2 curl icu4c libedit libjpeg libiconv libpng libxml2 libzip openssl re2c tidy-html5 zlib
$ CONFIGURE_OPTS="--with-zlib-dir=$(brew --prefix zlib) --with-bz2=$(brew --prefix bzip2) --with-curl=$(brew --prefix curl) --with-iconv=$(brew --prefix libiconv) --with-libedit=$(brew --prefix libedit) --with-readline=$(brew --prefix readline) --with-tidy=$(brew --prefix tidy-html5)" 
phpenv install [your desired php version]
```
You can obviously play around with the various configuration options yourself. Give this approach a try and let us know if that works. It's definitely neater and doesn't require you to disable SIP.

I hope it helps.

**Comment by epicsagas** [comment]
@debo Yes, I have tried with that options without disabling SIP, but encountered kind of “/usr/include” path error(cannot remember that now, will update later). And please remind that I said this is just temporary solution and unsafe way.

However I will try that solution again from the beginning. 

And I think that configures you have mentioned need to be announced if that is worked properly.

**Comment by epicsagas** [comment]
> Hi @epicsagas I would personally discourage to use your solution. Did you have a look at the other [open issue for Mojave](https://github.com/phpenv/phpenv/issues/90)? The underlying problem is the same. There are few approaches in there but I'd say a good compromise of all those would be the following:
> 
> ```shell
> $ brew install autoconf bison bzip2 curl icu4c libedit libjpeg libiconv libpng libxml2 libzip openssl re2c tidy-html5 zlib
> $ CONFIGURE_OPTS="--with-zlib-dir=$(brew --prefix zlib) --with-bz2=$(brew --prefix bzip2) --with-curl=$(brew --prefix curl) --with-iconv=$(brew --prefix libiconv) --with-libedit=$(brew --prefix libedit) --with-readline=$(brew --prefix readline) --with-tidy=$(brew --prefix tidy-html5)" phpenv install [your desired php version]
> ```
> 
> You can obviously play around with the various configuration options yourself. Give this approach a try and let us know if that works. It's definitely neater and doesn't require you to disable SIP.
> 
> I hope it helps.

@debo I have missed some installation with brew. I have tried with this solution with brewing  and worked like a charm! 

Please mention this configure options on documentations.

**Comment by debo** [comment]
No problem @epicsagas I'm glad it helped. I'll add something to it later today, however keep in mind that also this is a temporary solution. We are still waiting for the php and php-build team to provide a more permanent solution similar to the one adopted by the other xEnv tools. This issue unfortunately as you know it's caused by OSX itself so we need to workaround its quirks without breaking things for other users on earlier versions.

**Comment by Lewiscowles1986** [comment]
This does not work for 8.4.7 on OSX in 2025
