### ISSUE TITLE
How to install LDAP extension 

### ISSUE THREAD

**Issue by gweecl** [phpenv/phpenv#99]
I am trying to install `php 7.1.33` with LDAP:
`--with-ldap=$(brew --prefix openldap)`

But I am getting this error:
```bash
configure: error: Don't know how to define struct flock on this system, set --enable-opcache=no
```

Any idea ?

**Comment by debo** [comment]
Hi @gweecl did you try to follow the advice in the error message? Do you get the same error if you try that way? Please let us know.

**Comment by gweecl** [comment]
tried with `--enable-opcache`.  now wokring. thanks

**Comment by debo** [comment]
Perfect, I'm glad that helped. Enjoy!
